### ISSUE TITLE
as a user, I would like to toggle the to do list view to a calendar view

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#1013]
as a user, I would like to toggle the to do list view to a calendar view to visualize my to do in a calendar and perform add/edit that goes back to the to do list so the fields have to be identical

![image](https://user-images.githubusercontent.com/3675043/193378522-55514076-cf72-418c-89c4-3aff310c9a8b.png)

**Comment by b-solution** [comment]
@bluenevus hi there. Hope so you are doing well. I am confused in some things. See steps below

- 1st of all if one of the user creates a todo and don’t add date. If he wishes to toggle to calendar on which date should i display that todo

![image](https://user-images.githubusercontent.com/5988861/195099615-7cc54273-674a-4959-9b22-d750ca9b9b32.png)

- Secondly I want to ask you if you want event reminders as sort of in calendar we had. More simply they will also be added in todo if you wish because you are saying for toggling and in doing so we have to do the same.

![image (1)](https://user-images.githubusercontent.com/5988861/195099712-40892385-f1cd-4fbf-924f-a6f63e0e1edd.png)

**Comment by b-solution** [comment]
@bluenevus hi there. Hope so you are doing well. I am confused in some things. See steps below

- 1st of all if one of the user creates a todo and don’t add date. If he wishes to toggle to calendar on which date should i display that todo

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/195100416-212f8c48-368c-4ecc-894d-62431f50e6e9.png">

- Secondly I want to ask you if you want event reminders as sort of in calendar we had. More simply they will also be added in todo if you wish because you are saying for toggling and in doing so we have to do the same.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5988861/195100757-c28b9689-65e8-4887-8a80-aca627c4025b.png">

**Comment by bluenevus** [comment]
if there are no dates, then we should grey out the button.  if there are dates, only the dates they have should show and the button should be active.  

I think notifications would be a good idea
