### ISSUE TITLE
Whiteboard map: When "Erase" is selected without an object being selected, it should function like an eraser.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#1593]
When "Erase" is selected without an object being selected, the sections of the board that the mouse is moved over should be erased (like on a chalkboard).
Screenshot Example

![ERASE_partially_unselected_object](https://github.com/MicroHealthLLC/mSuite/assets/11938477/610b9d09-02a6-4b22-8375-c87d3db5c6f4)

**Comment by LAlexMHllc** [comment]
NOTE: Even when there is only one object on the board, selecting the object and clicking "Forward" before trying to partially erase the object did not work.

**Comment by b-solution** [comment]
@LAlexMHllc I hope you are well.
The issue is not getting resolved, and I would like to inform this problem persists because the library lacks the required option. If we handle it by customizing and setting the color to white when selecting the eraser, it behaves like an eraser. However, a new issue arises when we pick up the erased object and place that object in the other position; the erased part remains in its previous position, and the selected object reverts to its original shape. This occurs because of the white color we have chosen upon selecting the eraser.

Link of Library:-
https://vigorous-heisenberg-7f8730.netlify.app/

https://github.com/MicroHealthLLC/mSuite/assets/5988861/61668c04-b898-429d-9b49-b7d5e4cb0d8d

**Comment by LAlexMHllc** [comment]
Closing, won't fix
