### ISSUE TITLE
mindmaps should be exportable to an image and/or PDF

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#160]
they should have an option for each either an image or pdf to export what they see

**Comment by bluenevus** [comment]
pdf functionality doesn't show in this pull 
![image](https://user-images.githubusercontent.com/3675043/148964076-897c0aa7-037a-49b1-8ab0-5a728c9ed927.png)
![image](https://user-images.githubusercontent.com/3675043/148964103-25523b8d-3791-4ae7-9210-96a927cc09d4.png)

**Comment by b-solution** [comment]
I hadn't merged the PR before but now since it is merged you can test it and let me know if there is any kind of problem.
<img width="1272" alt="Screenshot 2022-01-11 at 8 37 28 PM" src="https://user-images.githubusercontent.com/5988861/148974071-59c7b81a-3b98-46ba-960d-3f1443096011.png">
<img width="1276" alt="Screenshot 2022-01-11 at 8 36 52 PM" src="https://user-images.githubusercontent.com/5988861/148974115-7f5758ce-0746-466a-953a-5eebfbde1e68.png">
<img width="471" alt="Screenshot 2022-01-11 at 8 37 12 PM" src="https://user-images.githubusercontent.com/5988861/148974158-e4b1be26-4893-48cf-bbf9-a87ccb4558f4.png">
