### ISSUE TITLE
for each application, the user should be able to give it a Title:  that title should be in the center on the top header

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#250]
for each application, the user should be able to give it a Title:  that title should be in the center on the top header between the icons on the left and the right.  This should be as simple clicking the field to activate and typing then clicking away or entering or tab to lose focus and the name saves.  as simple as possible

![image](https://user-images.githubusercontent.com/3675043/147790373-2f110598-7c10-4416-854a-6683cdaed2ab.png)

**Comment by b-solution** [comment]
The Title in the middle of the navigation bar is only available for kanban and whiteboard since all other maps have their title already displayed and can be changed.
<img width="1280" alt="Screenshot 2021-12-31 at 6 39 59 PM" src="https://user-images.githubusercontent.com/5988861/147830484-d523bdd4-7923-4df1-a7e2-86d5daa697bb.png">
<img width="1274" alt="Screenshot 2021-12-31 at 6 40 14 PM" src="https://user-images.githubusercontent.com/5988861/147830488-9b4ef5d8-d434-4945-87ad-9e7b138aeef4.png">
