### ISSUE TITLE
Instead of displaying Alert when user inputs same Name with different character case, should display Same URL Modal.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#259]
When user tries to create a map with an existing name with different case letters, an "Unable to open/create mindmap" Alert displays.
Screenshot Example

![unable_to_open_create_mindmap_alert](https://user-images.githubusercontent.com/11938477/148412224-6ce9f0fd-4cec-4c4e-ba53-0d31295bd479.png)

More Screenshot Examples with different character case entry that caused alert to display.

![unable_to_open_create_mindmap_alert_2](https://user-images.githubusercontent.com/11938477/148412399-1925d41b-0bf9-4f03-b9a1-b1b5688e86fd.png)

**Comment by bluenevus** [comment]
if the name exists, it should take the user directly to the map.  its how they are getting back to the url

right now it says the name is already taken but the given name is so that a person can also get back to it from that

its upon the user to come up with a unique name or password protect it

**Comment by LAlexMHllc** [comment]
The issue here is character case sensitivity. The Alert displays when the character case does not match.

**Comment by b-solution** [comment]
@bluenevus If a new user enter any existing map name with tree map and we opened the map with kanban (because it exisits in our DB). The user get confused because user create different type of mSuite but suddenly open different mSuite.

That's way we are showing sweet modal So, user know that it's already exists and user have three option either open, try again or create random to select which way to go.

NOTE: I fixed the alert issue.

![image](https://user-images.githubusercontent.com/5988861/149336022-48448b6d-c00f-43ae-98de-001a56ffa47b.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it again. I've fixed this issue. If you do still face this issue let me know.

**Comment by LAlexMHllc** [comment]
@b-solution  Just tested again with the same results. Are you testing this with hyphens instead of blanks with different character case than saved URL? Look at screenshot in my prior comment,

**Comment by bluenevus** [comment]
everything up to date in terms of pull as of yesterday and confirmed still up to date just now
