### ISSUE TITLE
Mindmap: Fix line drawing and hand location when user creates a node

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#436]
When user pulls out a line, the hand location is no where near the line, so it's hard to figure out where the line is or where it will end up.
Screenshot Example

![mindmap_create_node_and_drag_node_weird](https://user-images.githubusercontent.com/11938477/162998890-4ac1a44c-f3bc-407c-a614-7a27d3f0e769.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example

![mindmap_user_prepares_to_pull_upward_to_create_node](https://user-images.githubusercontent.com/11938477/163005287-4beb8b4d-04b7-4d87-afdb-98fb808b5f49.png)

![mindmap_user_prepares_to_pull_upward_to_create_node_2](https://user-images.githubusercontent.com/11938477/163005299-715bff55-b421-40aa-828a-5e243844ef5e.png)

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed these issue can you please test it again and let me know if its not work.

**Comment by LAlexMHllc** [comment]
@b-solution Still not function correctly

**Comment by b-solution** [comment]
@LAlexMHllc  In my side every thing is working fine and you can see this in video.
https://user-images.githubusercontent.com/5988861/163771400-4cc268e5-6318-45da-aa54-8b55a64f118b.mp4

**Comment by bluenevus** [comment]
@bilel-kedidi  your mouse curser is not at the end of the line.  its about an inch away so users can't get a sense of where the line will end up.  Yes dragging the line works but the cursor should be at the tip of the line because that is where they are dragging like so https://www.mindmaps.app/  notice when you drag the line, the cursor is right ON the tip of the line so where you drop it is where you expect it to be
