### ISSUE TITLE
as a user I would like to collaborate on making a simple poll then share the link  only for pollsters to fill out but not be able to edit the questions that only the collaborators can do with a different link

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSuite#529]
As a user I would like to collaboratively create a poll.  That is questions and responses that can be picked by the the person being polled.  Simple that is question and free text, question and date selection, question and answers to pick from.  Then tally them up in a simple graph to the collaborators like so 
![image](https://user-images.githubusercontent.com/3675043/171688835-218aebd1-983e-4fb2-92a3-5d66cb784a5d.png)
but not visible to the person being polled in the read only link they have.

So the collaborators would have their own unique link that allows them to edit the form together and see the results of what has been polled like above.  Once done, they can send a separate read only link that users can fill out the question but not edit or see results...just respond to the poll.

**Comment by b-solution** [comment]
@bluenevus  I think this one is MRMS issue.

**Comment by LAlexMHllc** [comment]
Reopening, since Poll Map does not function as expected.
NOTE: Requirements for Poll Map are in progress.

**Comment by LAlexMHllc** [comment]
User (poll creator) wants to make an online Poll, potentially collaborating with others; then send the link to others to fill out and submit. Poll Results will be viewed on the Poll Collaborators Screen only.


POLL COLLABORATORS SCREEN

Poll creator should:
- Click the Poll Map box on the Index screen.
- Click the "Save" button on the top menu, then "Save Private" on the Poll Map that displays.
- If desired, share the URL with other poll collaborator(s).

Poll Form:
The "Create Poll" button should initially be disabled.
Poll collaborators should input required fields, and can input optional fields.
When the "Cancel" button on the Poll Form is clicked, the form should revert to the last saved input; otherwise, default.
When the "Save" button on the Poll Form is clicked, the form should be validated.
When the form fails validation, error message(s) should display.
When the form passes validation: the form input should be saved; a Success Message should display; and the "Create Poll" button should become enabled.
When the form is modified after the "Save" button is clicked, then "Create Poll" button should become disabled.
When the poll collaborators agree that the poll content is complete, then one of them should click the enabled "Create Poll" button.

Draft Poll:
When the enabled "Create Poll" button is clicked, a Draft Poll created using the Poll Form should display, replacing the Poll Form.
Poll collaborators should look over the Draft Poll to make sure it displays as expected.
When the "Cancel" button is clicked, the Poll Form will display, replacing the Draft Poll.
When poll collaborators agree that the Poll is ready to be finalized, one of them should click the "FINALIZE" button on the Draft Poll.

Finalized Poll:
When the "FINALIZE" button is clicked on the Draft Poll: the Finalized Poll will display as read only (disabled); the "FINALIZE" text should be replaced with "SUBMIT"; and the "CANCEL" text should be replaced with "RESET".
Poll Collaborators should send the Poll URL to users to fill out the Poll.

Poll Results:
The Poll Results should display on the Poll Collaborators screen.
User should be able to select a graph type to display the results for each question.

Poll collaborator should click the “Export” button with the image icon, then choose to download the screen in PDF or image (PNG) format.
Poll collaborator should click the “Export” button with the “X” icon, then choose to download the Poll Results in Excel or CSV format.


USER POLL SCREEN

Poll Taker should input their User Name by clicking the "User" button on the top header bar, then input their Name on the modal that displays.
Poll Taker should fill out the Poll that displays at the Poll URL that was sent to them. When a Poll Expiration Date displays on the header bar, user should submit the poll before it expires.
When the user wants a copy of the Poll, they should click the "Export" button, then choose to download PDF or image, before clicking "SUBMIT".
When a validation error message display after "SUBMIT' was clicked, the user should edit the Poll, then submit.
Poll Taker should only be able to successfully submit the Poll once.
