### ISSUE TITLE
All Maps: Include "Undo" and "Redo" buttons on header bar, since Confirm/Delete function will be removed. 

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#604]
For Undo and Redo: minimum 10, preferably 20

**Comment by bluenevus** [comment]
like so in the header so they can undo or redo all any action.  particularly important since confirmation of delete is being removed #603 #602 which will get rid of the constant nagging when editing a document for deletes.  

![image](https://user-images.githubusercontent.com/3675043/173137683-8af8ccf7-8502-442d-a305-363506ad4d66.png)

**Comment by b-solution** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5988861/180737829-c926af9b-2257-468f-b177-571dc8e072be.png">

@LAlexMHllc @bluenevus I have added this functionality. Kindly test it.

**Comment by LAlexMHllc** [comment]
Reopening, since Undo/Redo buttons are missing on top menu bar for Mindmap and Notepad.

Whiteboard and Spreadsheet should have Undo/Redo buttons moved to the top menu bar, and be styled consistent to other buttons.

Clicking Undo/Redo should  undo/redo all action steps.

**Comment by LAlexMHllc** [comment]
**NOTE: Undo/Redo object attributes, etc, should be included as an enhancement in the future.**

**Comment by LAlexMHllc** [comment]
Undo/Redo missing from:
- Mindmap
- Notepad
- Spreadsheet
- Poll

Whiteboard still has Redo/Undo on sidebar menu instead of header bar
