### ISSUE TITLE
TreeMap - Should not be able to update background color for new node without saved Title.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#632]
To be consistent with other maps, Color Picker should not display when "pencil" clicked on object without saved Title
Screenshot Example

![treeMap_should_not_be_able_change_background_color_of_node_without_saved_Title](https://user-images.githubusercontent.com/11938477/173883619-c0a060fe-fcf7-4c51-a137-a658f6f582ac.png)

**Comment by bluenevus** [comment]
too many rules.  if we want to be consistent we want to UNDO any requirements of a title to change color because we should NOT restrict users and force them into a workflow to save a title before changing color.  LOW friction and this rule adds friction

we need to fix this everywhere else and there should be NO requirements to save a title to simply chang ethe color..
