### ISSUE TITLE
Remove "Title" requirement from all objects (new and edit)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#634]
This refers to node objects, map objects; NOT the Title on the header bar (which is currently not required).

**Comment by bluenevus** [comment]
the user shouldn't be boxed in a rule to enter a title on a node before doing an action like color picker.  I may want to create a flow map with x number of nodes then put the names in after...so what?  I may want to map out a few treemap nodes then enter a title then put a color.  why box them into a specific workflow.  low friction.  let them do what they need to do.  I know when I do an org chart, I have like a structure that has to be done and will put in the names later.  But  can't do that because there is a rule only letting me add ONE node and putting in a node title.  a rule that says I have to have a title before I can apply a color.  why put these rules on users on how they want to cllaborate.  Liberate the collaboration and let them do things without dictating a workflow like put this title first before you can move to the next aspect of your collaboration

**Comment by b-solution** [comment]
@LAlexMHllc @bluenevus Can you please test it.

**Comment by LAlexMHllc** [comment]
TreeMap, TreeChart, FlowMap - FIXED

Kanban - Still needs to be fixed

**Comment by b-solution** [comment]
@LAlexMHllc I've fixed this. Can you please test it again.
