### ISSUE TITLE
users should be able to identify other users collaborating on a map by temporary user like user 1 that they can edit to something like Joe

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSuite#682]
Include temporary user name like user 1, user 2, user 3, user 4.
Each user can change their user # to an alternate Name (Example: User 1 can change it to "Joe")
Display the user id or alternate Name when the map is being Edited by that user.
EXAMPLE
User 1 Editing...
Joe Editing...

**Comment by bluenevus** [comment]
The purpose is so that users can identify who is editing.  By default, everyone there is just user 1, user 2, user 3.  For simple collaboration that is no big deal but they can identify others who are editing.  However more complex, they may want to know joe or jane.  By giving the er to change their temporary user name from user 1 to Joe, it give them the ability to identify themselves.  This is where cookies become important because the cookie will identify themselves the same way for every map and and next time they open the link .  so I don't have to keep changing user 1 to joe because there is a cookie where it knows I'm joe everytime I open a map by default.  Of course if cookies clear, they are back to user 1 and if they go to a new computer they are back to user 1.

**Comment by LAlexMHllc** [comment]
"Undefined" should be replaced by User <id#> by default, unless user input Name.
Screenshot Example

![editing_should_be_User_ID_by_default_instead_of_undefined](https://user-images.githubusercontent.com/11938477/184217503-5975e8c9-6d99-4c4a-970a-7003a32f0a8c.png)

NOTE: Also see related Issue #796

**Comment by LAlexMHllc** [comment]
Should not update User Name to blank
Screenshot Example

![should_not_update_Username_to_blank](https://user-images.githubusercontent.com/11938477/184222405-00eb6b11-f17b-4de8-ac90-5cb5ee8b2b1c.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test with latest pull i've fixed this issue yesterday and let me know if it's not working.

**Comment by LAlexMHllc** [comment]
User Id# should not be duplicate. Sometimes when User Name removed (left blank), when user edits the map it will display a duplicate User Id# when collaborating.

**Comment by LAlexMHllc** [comment]
Last code update replaced empty User Name with 5 random characters.
Screenshot Example

![maps_user_name_replaced_by_5_random_characters_when_left_empty](https://user-images.githubusercontent.com/11938477/184920429-cb788098-c75b-4911-95f0-c6a3e496158c.png)

However, User Name still accepted blank(s) when edited. When Close is clicked on the User Name modal, should validate that trim(UserName) is not blank. When blank, should display validation error instead of closing modal.
Screenshot Example

![validate_trim_UserName_is_not_blank_when_Close_clicked](https://user-images.githubusercontent.com/11938477/184925893-636858ab-596e-4ff4-8ed3-c79e562ed263.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
